export const THEMES_DATA = {
  // ======== METAL ========

  metal: {
    name: 'Bandas de Metal Internacional',
    singular: 'banda de metal',
    gender: 'a',
    items: [
      "Metallica",
      "Iron Maiden",
      "Black Sabbath",
      "Judas Priest",
      "Slayer",
      "Megadeth",
      "Pantera",
      "Anthrax",
      "Sepultura",
      "Death",
      "Cannibal Corpse",
      "Morbid Angel",
      "Possessed",
      "Obituary",
      "Deicide",
      "Mayhem",
      "Darkthrone",
      "Burzum",
      "Emperor",
      "Immortal",
      "Bathory",
      "Venom",
      "Celtic Frost",
      "Mercyful Fate",
      "Sodom",
      "Kreator",
      "Destruction",
      "Exodus",
      "Testament",
      "Overkill",
      "Dark Angel",
      "Arch Enemy",
      "Children of Bodom",
      "In Flames",
      "At The Gates",
      "Carcass",
      "Napalm Death",
      "Entombed",
      "Dismember",
      "Bolt Thrower",
      "Opeth",
      "Gojira",
      "Mastodon",
      "Lamb of God",
      "Meshuggah",
      "Dream Theater",
      "Tool",
      "System of a Down",
      "Rammstein",
      "Nightwish",
      "Motörhead",
      "Dio",
      "Accept",
      "Helloween",
      "Saxon",
      "Rainbow",
      "Scorpions",
      "Manowar",
      "Annihilator",
      "Voivod",
      "Machine Head",
      "Korn",
      "Slipknot",
      "Disturbed",
      "Avenged Sevenfold",
      "Ghost",
      "Sabaton",
      "Gwar",
      "Trivium",
      "Cradle of Filth",
      "Kamelot",
      "Gamma Ray",
      "Blind Guardian",
      "Stratovarius",
      "HammerFall",
      "DragonForce",
      "Iced Earth",
      "Primal Fear",
      "Savatage",
      "King Diamond",
      "Type O Negative",
      "Fear Factory",
      "Behemoth",
      "Amon Amarth",
      "Jinjer",
      "Powerwolf",
      "Suffocation",
      "Immolation",
      "Dying Fetus",
      "Dark Tranquillity",
      "Insomnium",
      "Enslaved",
      "Crimson Glory",
      "Atheist",
      "Symphony X",
      "Queensrÿche",
      "W.A.S.P.",
      "Anvil",
      "Corrosion of Conformity",
      "High on Fire",
      "Municipal Waste",
      "Gorgoroth",
      "Candlemass",
      "Sirenia",
      "Ensiferum",
      "Eluveitie",
      "Myrath",
      "Dark Funeral",
      "Power Trip",
      "Exhorder",
      "Kylesa",
      "Between the Buried and Me",
      "Ne Obliviscaris",
      "Decapitated",
      "Beast in Black",
      "Shadows Fall",
      "Obscura",
      "Dimmu Borgir",
      "Satyricon",
      "Devin Townsend",
      "Paradise Lost",
      "Parkway Drive",
      "Crowbar",
      "Blood Incantation",
      "Agalloch",
      "Acid Bath",
      "Alcest",
      "Tiamat",
      "Moonspell",
      "Septicflesh",
      "Rotting Christ",
      "Katatonia",
      "My Dying Bride",
      "Gorefest",
      "Pestilence",
      "Vader",
      "Augury",
      "Leprous",
      "Soilwork",
      "Darkane",
      "Marduk",
      "Doro",
      "Savage Messiah",
      "Killswitch Engage",
      "Steel Panther",
      "Heaven Shall Burn",
      "Revocation",
      "Vektor",
      "Sólstafir",
      "Wintersun"
    ]
  },

  metalChile: {
    name: 'Bandas de Metal Chileno',
    singular: 'banda de metal chilena',
    gender: 'a',
    items: [
      'Pentagram', 'Criminal', 'Dorso', 'Atomic Aggressor', 'Torture',
      'Sadism', 'Masacre', 'Totten Korps', 'Coffin Curse', 'Orator',
      'Unholyforce', 'Thornafire', 'Demonic Rage', 'Cancerbero', 'Demoniac',
      'Warpath', 'Poema Arcanus', 'Mar de Grises', 'Procession', 'Lethal',
      'Panzer', 'Battlerage', 'Rancor', 'Vastator', 'Force of Darkness',
      'Communion', 'Grave Desecrator', 'Wrathprayer', 'Slaughtbbath', 'Godless',
      'Parkcrest', 'DevilPreacher', 'Fosa Común', 'Machuca', 'Yajaira',
      'Inanna', 'Kuervos del Sur', 'Escombro', 'Dogma', 'Dekapited',
      'Eternal Sacrifice', 'Ripper', 'Soulfly Chile', 'Thy Antichrist', 'BlackStorm',
      'Darkness', 'Inherited', 'Iron Attack', 'Legacy of Brutality', 'Steel Bearing Hand',
      "Necrosis",
      "Six Magics",
      "Death Yell",
      "Sobernot",
      "Asunto",
      "Total Mosh",
      "Delta",
      "Apostasy",
      "Ancient Crypts",
      "Defacing",
      "Piggy",
      "Phantasmagore",
      "Esophagus",
      "Unaussprechlichen Kulten",
      "Hateworks",
      "Sikario",
      "Nocturnal",
      "Blodskam",
      "Klauzer",
      "Weight of Emptiness",
      "Doskras",
      "Chaicura",
      "Undercroft",
      "Gangrena",
      "Necrodemon",
      "We Are The Monster",
      "Dark God",
      "Suppression",
      "Horrifying",
      "Rotten Tomb",
      "Hallux Valgus",
      "Trastorned",
      "Perversor",
      "Atomicide",
      "Invocation Spells",
      "Miserycore",
      "Necroripper",
      "Acero Letal",
      "Motosierra",
      "Hellish",
      "Mayhemic",
      "Ritual of Flesh",
      "Gravered",
      "Exanimatvm",
      "Heráldica de Mandrake",
      "Lucifer's Hammer",
      "Uaral",
      "All Tomorrows",
      "Parasyche",
      "Mawiza",
      "Vórtize",
      "Sepulcrum",
      "Weichafe",
      "Nuclear",
      "Novus Ordo",
      "Wangalen",
      "Black Moon",
      "Chaos Magic",
      "Critical Defiance",
      "Racer Steel",
      "Neural Dissonance",
      "Abyssarium",
      "Krematorium",
      "Catalepsia",
      "Abominy",
      "Seas of Torment",
      "Fiebre Séptica",
      "Aquer",
      "Sarcophigadae",
      "Endeium",
      "D1STRAUGHT",
      "TREGUL",
      "Plegaria",
      "Darkness Eternal",
      "Diabolical Messiah",
      "Venoject",
      "Sarca"
    ]
  },

  metalAlbums: {
    name: 'Discos de Metal',
    singular: 'disco de metal',
    gender: 'o',
    items: [
      'Master of Puppets (Metallica)',
      'Reign in Blood (Slayer)',
      'Painkiller (Judas Priest)',
      'Paranoid (Black Sabbath)',
      'Rust in Peace (Megadeth)',
      'Blackwater Park (Opeth)',
      'Leviathan (Mastodon)',
      'At the Heart of Winter (Immortal)',
      'Altars of Madness (Morbid Angel)',
      'Symbolic (Death)',
      'Crimson (Edge of Sanity)',
      'Powerslave (Iron Maiden)',
      'De Mysteriis Dom Sathanas (Mayhem)',
      'In the Nightside Eclipse (Emperor)',
      'Transilvanian Hunger (Darkthrone)',
      'The Bleeding (Cannibal Corpse)',
      'Left Hand Path (Entombed)',
      'Like an Ever Flowing Stream (Dismember)',
      'Pierced from Within (Suffocation)',
      'Epicus Doomicus Metallicus (Candlemass)',
      'Black One (Sunn O)))',
      'Ghost Reveries (Opeth)',
      'Lateralus (Tool)',
      'Crack the Skye (Mastodon)'
    ]
  },

  // ======== FÚTBOL ========

  soccer: {
    name: 'Jugadores de Fútbol',
    singular: 'jugador de fútbol',
    gender: 'o',
    items: [
      'Lionel Messi', 'Cristiano Ronaldo', 'Pelé', 'Diego Maradona', 'Johan Cruyff',
      'Zinedine Zidane', 'Ronaldo Nazário', 'Ronaldinho', 'Franz Beckenbauer', 'Alfredo Di Stéfano',
      'Michel Platini', 'Marco van Basten', 'George Best', 'Bobby Charlton', 'Lev Yashin',
      'Gerd Müller', 'Paolo Maldini', 'Franco Baresi', 'Lothar Matthäus', 'Roberto Baggio',
      'Romário', 'Rivaldo', 'Thierry Henry', 'Andrés Iniesta', 'Xavi Hernández',
      'Neymar Jr', 'Kylian Mbappé', 'Erling Haaland', 'Robert Lewandowski', 'Karim Benzema',
      'Luka Modrić', 'Kevin De Bruyne', 'Mohamed Salah', 'Sergio Ramos', 'Virgil van Dijk',
      'Manuel Neuer', 'Gianluigi Buffon', 'Iker Casillas', 'Luis Suárez', 'Sergio Agüero',
      'Zlatan Ibrahimović', 'Wayne Rooney', 'Frank Lampard', 'Steven Gerrard', 'Andrea Pirlo',
      'Gareth Bale', 'Eden Hazard', 'Sadio Mané', 'Harry Kane', 'Son Heung-min'
    ]
  },

  soccerTeams: {
    name: 'Equipos de Fútbol',
    singular: 'equipo de fútbol',
    gender: 'o',
    items: [
      'Real Madrid',
      'Barcelona',
      'Manchester United',
      'Liverpool',
      'Bayern Munich',
      'AC Milan',
      'Juventus',
      'Inter Milan',
      'Ajax',
      'Benfica',
      'Porto',
      'PSG',
      'Manchester City',
      'Chelsea',
      'Arsenal',
      'Borussia Dortmund',
      'Atlético Madrid',
      'Valencia',
      'Sevilla',
      'Sporting CP',
      'Celtic',
      'Rangers',
      'Feyenoord',
      'PSV',
      'Anderlecht',
      'Marseille',
      'Lyon',
      'Monaco',
      'Boca Juniors',
      'River Plate',
      'São Paulo',
      'Santos',
      'Flamengo',
      'Palmeiras',
      'Corinthians',
      'Peñarol',
      'Nacional',
      'Independiente',
      'Racing',
      'San Lorenzo',
      'Colo-Colo',
      'Universidad de Chile',
      'Universidad Católica',
      'América',
      'Chivas',
      'Galatasaray',
      'Fenerbahçe',
      'Al Ahly',
      'Kaizer Chiefs',
      'LA Galaxy',
      'Atlético Mineiro',
      'Fluminense',
      'Vasco da Gama',
      'Gremio',
      'Internacional',
      'Athletic Club',
      'Real Sociedad',
      'Betis',
      'Celta de Vigo',
      'Espanyol',
      'Villarreal',
      'Lazio',
      'Roma',
      'Napoli',
      'Fiorentina',
      'Torino',
      'Atalanta',
      'Sampdoria',
      'Udinese',
      'Bayer Leverkusen',
      'Schalke 04',
      'Hamburgo',
      'Werder Bremen',
      'VfL Wolfsburg',
      'Eintracht Frankfurt',
      'RB Leipzig',
      'Independiente Santa Fe',
      'Atlético Nacional',
      'Millonarios',
      'Deportivo Cali',
      'Universidad de Concepción',
      'Unión Española',
      'Audax Italiano',
      'Universidad de San Martín',
      'Alianza Lima',
      'Sporting Cristal',
      'Huracán',
      'Vélez Sarsfield',
      'Lanús',
      'Newell\'s Old Boys',
      'Rosario Central'
    ]
  },

  soccerChile: {
    name: 'Equipos de Fútbol Chileno',
    singular: 'equipo de fútbol chileno',
    gender: 'o',
    items: [
      'Colo-Colo', 'Universidad de Chile', 'Universidad Católica', 'Unión Española',
      'Palestino', 'Audax Italiano', 'Cobresal', 'Huachipato', 'Everton',
      'Coquimbo Unido', 'O’Higgins', 'Curicó Unido', 'Deportes La Serena',
      'Deportes Antofagasta', 'Ñublense', 'Deportes Iquique',

      'Cobreloa', 'Santiago Wanderers', 'Magallanes', 'Barnechea',
      'Santiago Morning', 'San Luis de Quillota', 'Deportes Puerto Montt',
      'Deportes Temuco', 'Rangers', 'Unión San Felipe', 'Deportes Recoleta',
      'Deportes Santa Cruz',

      'General Velásquez', 'Deportes Valdivia', 'Deportes Concepción',
      'Real San Joaquín', 'Independiente de Cauquenes', 'Trasandino',
      'Rodelindo Román', 'Limache', 'Melipilla'
    ]
  },

  // ======== NUEVAS CATEGORÍAS ========

  cars: {
    name: 'Automóviles',
    singular: 'automóvil',
    gender: 'o',
    items: [
      'Mazda CX-30',
      'Mazda 3',
      'Volkswagen Gol',
      'Volkswagen Polo',
      'Toyota Corolla',
      'Toyota Yaris',
      'Toyota RAV4',
      'Honda Civic',
      'Honda Fit',
      'Kia Morning',
      'Kia Rio',
      'Kia Sportage',
      'Hyundai Tucson',
      'Hyundai Elantra',
      'Hyundai Accent',
      'Chevrolet Sail',
      'Chevrolet Spark',
      'Chevrolet Tracker',
      'Nissan Versa',
      'Nissan Kicks',
      'Nissan X-Trail',
      'Suzuki Swift',
      'Suzuki Baleno',
      'Suzuki Vitara',
      'Ford Focus',
      'Ford Fiesta',
      'Ford Explorer',
      'Jeep Renegade',
      'Jeep Compass',
      'Subaru Forester',
      'Subaru Outback',

      'Volkswagen Tiguan',
      'Volkswagen Jetta',
      'Toyota Hilux',
      'Toyota Camry',
      'Honda HR-V',
      'Honda CR-V',
      'Kia Sorento',
      'Hyundai Santa Fe',
      'Hyundai Kona',
      'Chevrolet Onix',
      'Nissan Sentra',
      'Nissan Murano',
      'Suzuki Vitara Brezza',
      'Ford EcoSport',
      'Ford Ranger',
      'Jeep Grand Cherokee',
      'Subaru XV',
      'Mazda CX-5',
      'Mazda 6',

      'Toyota Yaris Cross',
      'Toyota Prius',
      'Mazda CX-3',
      'Volkswagen Golf',
      'Volkswagen Passat',
      'Volkswagen Beetle',
      'BMW 3 Series',
      'BMW 5 Series',
      'Audi A3',
      'Audi A4',
      'Mercedes-Benz C-Class',
      'Mercedes-Benz E-Class',
      'Porsche 911',
      'Porsche Cayenne',
      'Lexus RX',
      'Lexus IS',
      'Nissan Leaf',
      'Tesla Model 3',
      'Tesla Model S',
      'Tesla Model Y',
      'Hyundai Ioniq 5',
      'Kia EV6',
      'Jaguar F-Pace',
      'Jaguar XE',
      'Land Rover Discovery',
      'Land Rover Defender',
      'Mitsubishi Outlander',
      'Mitsubishi ASX',
      'Renault Clio',
      'Renault Megane',
      'Peugeot 208',
      'Peugeot 3008',
      'Citroën C3',
      'Fiat 500',
      'Fiat Panda',
      'Skoda Octavia',
      'Skoda Superb',
      'Seat Leon',
      'Seat Ibiza',
      'Mini Cooper',
      'Alfa Romeo Giulia',
      'Alfa Romeo Stelvio',
      'Dacia Duster',
      'Renault Captur',
      'Opel Corsa',
      'Opel Astra',
      'Chevrolet Cruze',
      'Chevrolet Malibu',
      'Kia Stonic',
      'MG ZS',
      'Mazda MX-5',
      'Subaru Impreza',
      'Subaru Legacy',
      'Toyota Land Cruiser',
      'Mitsubishi Pajero',
      'Ford Mustang',
      'Chevrolet Camaro',
      'Dodge Charger',
      'Ferrari Portofino',
      'Lamborghini Huracán',
      'Aston Martin Vantage',
      'Rolls-Royce Phantom',
      'Bentley Continental GT',
      'Maserati Ghibli',
      'Jaguar E‑Type',
      'Volvo XC60',
      'Volvo S60',
      'Volvo V90',
      'Audi Q5',
      'Audi Q7',
      'Mercedes‑Benz GLC',
      'Mercedes‑Benz GLE',
      'Porsche Macan',
      'Porsche Panamera',
      'Lexus NX',
      'Lexus LX',
      'Infiniti Q50',
      'Infiniti QX60',
      'Nissan Pathfinder',
      'Honda Pilot',
      'Kia Telluride',
      'Hyundai Palisade',
      'Subaru Ascent',
      'Volkswagen Arteon'
    ]
  },

  drinks: {
    name: 'Tragos',
    singular: 'trago',
    gender: 'o',
    items: [
      'Piscola', 'Piscola con blanca', 'Piscola con negra',
      'Cerveza', 'Michelada', 'Terremoto',
      'Ponche de melón', 'Ponche de durazno',
      'Whisky-cola', 'Ron-cola', 'Vodka-naranja',
      'Jagerbomb', 'Fernet con Coca', 'Mojito',
      'Pisco Sour', 'Cola de mono', 'Vermut',
      'Pipeño', 'Chicha', 'Borgoña', 'Melón con vino',
      'Aperol Spritz', 'Vodka tónica', 'Gin Tonic', 'Grapa', 'Chuflai', 'Chupilca del diaulo',
      'Chicha de manzana', 'Sangría'
    ]
  },

  food: {
    name: 'Comidas Típicas',
    singular: 'comida',
    gender: 'a',
    items: [
      'Pizza', 'Sushi', 'Tacos', 'Hamburguesa',
      'Paella', 'Pad Thai', 'Ramen', 'Curry Indio',
      'Asado de vacuno', 'Ceviche', 'Empanada de Pino', 'Croissant Dulce',
      'Falafel', 'Kebab', 'Lasaña', 'Risotto', 'Gyoza',
      'Porotos con rienda', 'Asado de cordeno', 'Biryani', 'Shawarma', 'Completos',
      'Pastel de Choclo', 'Empanada Frita de Queso', 'Empanada Frita de Mariscos', 'Pescado Frito', 'Cazuela de Ave',
      'Cazuela de Vacuno', 'Fideos con Salsa de Tomate', 'Bistec con Arroz', 'Bistec con Papas Fritas', 'Pollo Arvejado',
      'Puré con Vienesas', 'Bistec a lo Pobre', 'Barros Jarpa', 'Choripán', 'Sopaipillas',
      'Sashimi', 'Tempura', 'Aji de gallina', 'Pan con Manjar', 'Pan con Palta',
      'Gnoccis', 'Ravioles', 'Pan con mortadela', 'Lasaña', 'Churros'
    ]
  },
  series: {
    name: 'Series de TV',
    singular: 'serie',
    gender: 'a',
    items: [
      'Breaking Bad', 'Game of Thrones', 'The Sopranos', 'The Wire', 'Friends',
      'The Office', 'Stranger Things', 'The Crown', 'Sherlock', 'Black Mirror',
      'Westworld', 'True Detective', 'Mad Men', 'Lost', 'The Walking Dead',
      'Dexter', 'House of Cards', 'Narcos', 'Peaky Blinders', 'Money Heist',
      'Dark', 'Chernobyl', 'Band of Brothers', 'The Mandalorian', 'The Witcher',
      'Vikings', 'Better Call Saul', 'Fargo', 'Twin Peaks', 'The X-Files',
      'Seinfeld', 'Curb Your Enthusiasm', 'Parks and Recreation', 'Brooklyn Nine-Nine', 'Community',
      'Rick and Morty', 'BoJack Horseman', 'Arcane', 'The Last of Us', 'Succession',
      'The Boys', 'Invincible', 'Fleabag', 'The Handmaid\'s Tale', 'Ozark',
      'Mindhunter', 'Squid Game', 'Wednesday', 'The Bear', 'Severance'
    ]
  },

  movies: {
    name: 'Películas',
    singular: 'película',
    gender: 'a',
    items: [
      'The Godfather', 'The Shawshank Redemption', 'Pulp Fiction', 'The Dark Knight', 'Schindler\'s List',
      'Forrest Gump', 'Fight Club', 'Inception', 'The Matrix', 'Goodfellas',
      'Star Wars', 'The Lord of the Rings', 'Interstellar', 'The Silence of the Lambs', 'Saving Private Ryan',
      'Se7en', 'The Departed', 'Gladiator', 'The Prestige', 'The Green Mile',
      'Memento', 'Apocalypse Now', 'The Usual Suspects', 'American History X', 'Léon: The Professional',
      'The Pianist', 'Parasite', 'Whiplash', 'The Shining', 'Alien',
      'Blade Runner', 'Terminator 2', 'Jurassic Park', 'Back to the Future', 'Die Hard',
      'Mad Max: Fury Road', 'No Country for Old Men', 'There Will Be Blood', 'Drive', 'The Grand Budapest Hotel',
      'Her', 'La La Land', 'Jojo Rabbit', 'Knives Out', 'Everything Everywhere All at Once',
      'Oppenheimer', 'Dune', 'The Batman', '1917', 'Joker'
    ]
  },
};
